### ISSUE TITLE
Provide pydux.create_store, pydux.extend, etc. 

### ISSUE THREAD

**Issue by kasbah** [benjamin9999/pydux#2]
Hey, thanks for this. Looking to move our [Braille reader UI](https://github.com/Bristol-Braille/canute-ui) over to using it. 

Would be good if the top level functions were re-exported from `__init__.py` so that you can do, for instance:

``` python
import pydux
pydux.create_store(reducer)
```

**Comment by usrlocalben** [comment]
added with ed1eaa1
